# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bsa.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 806)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pte_behav_strings = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_behav_strings.setObjectName("pte_behav_strings")
        self.verticalLayout.addWidget(self.pte_behav_strings)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leStringsFileName = QtWidgets.QLineEdit(self.centralwidget)
        self.leStringsFileName.setText("")
        self.leStringsFileName.setReadOnly(True)
        self.leStringsFileName.setObjectName("leStringsFileName")
        self.horizontalLayout.addWidget(self.leStringsFileName)
        self.pb_select_behav_strings_file = QtWidgets.QPushButton(self.centralwidget)
        self.pb_select_behav_strings_file.setObjectName("pb_select_behav_strings_file")
        self.horizontalLayout.addWidget(self.pb_select_behav_strings_file)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pb_statistics = QtWidgets.QPushButton(self.centralwidget)
        self.pb_statistics.setObjectName("pb_statistics")
        self.horizontalLayout_5.addWidget(self.pb_statistics)
        self.pb_save_observed_matrix = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save_observed_matrix.setObjectName("pb_save_observed_matrix")
        self.horizontalLayout_5.addWidget(self.pb_save_observed_matrix)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pte_statistics = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_statistics.setReadOnly(True)
        self.pte_statistics.setObjectName("pte_statistics")
        self.verticalLayout.addWidget(self.pte_statistics)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rb_percent_after_behav = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_percent_after_behav.setChecked(True)
        self.rb_percent_after_behav.setObjectName("rb_percent_after_behav")
        self.horizontalLayout_9.addWidget(self.rb_percent_after_behav)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.le_cutoff_transition_after_behav = QtWidgets.QLineEdit(self.centralwidget)
        self.le_cutoff_transition_after_behav.setObjectName("le_cutoff_transition_after_behav")
        self.horizontalLayout_4.addWidget(self.le_cutoff_transition_after_behav)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rb_percent_total_transitions = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_percent_total_transitions.setObjectName("rb_percent_total_transitions")
        self.horizontalLayout_10.addWidget(self.rb_percent_total_transitions)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.le_cutoff_total_transition = QtWidgets.QLineEdit(self.centralwidget)
        self.le_cutoff_total_transition.setObjectName("le_cutoff_total_transition")
        self.horizontalLayout_8.addWidget(self.le_cutoff_total_transition)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.rb_fraction_after_behav = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_fraction_after_behav.setObjectName("rb_fraction_after_behav")
        self.verticalLayout.addWidget(self.rb_fraction_after_behav)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pb_graphviz_script = QtWidgets.QPushButton(self.centralwidget)
        self.pb_graphviz_script.setObjectName("pb_graphviz_script")
        self.horizontalLayout_6.addWidget(self.pb_graphviz_script)
        self.pb_flow_diagram = QtWidgets.QPushButton(self.centralwidget)
        self.pb_flow_diagram.setObjectName("pb_flow_diagram")
        self.horizontalLayout_6.addWidget(self.pb_flow_diagram)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_block_first_behavior = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_block_first_behavior.setObjectName("cb_block_first_behavior")
        self.horizontalLayout_2.addWidget(self.cb_block_first_behavior)
        self.cb_block_last_behavior = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_block_last_behavior.setObjectName("cb_block_last_behavior")
        self.horizontalLayout_2.addWidget(self.cb_block_last_behavior)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.pte_excluded_transitions = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pte_excluded_transitions.setObjectName("pte_excluded_transitions")
        self.verticalLayout.addWidget(self.pte_excluded_transitions)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.leNumberRandomizations = QtWidgets.QLineEdit(self.centralwidget)
        self.leNumberRandomizations.setObjectName("leNumberRandomizations")
        self.horizontalLayout_3.addWidget(self.leNumberRandomizations)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.sb_nb_cores = QtWidgets.QSpinBox(self.centralwidget)
        self.sb_nb_cores.setMinimum(1)
        self.sb_nb_cores.setObjectName("sb_nb_cores")
        self.horizontalLayout_3.addWidget(self.sb_nb_cores)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pb_run_randomization_test = QtWidgets.QPushButton(self.centralwidget)
        self.pb_run_randomization_test.setObjectName("pb_run_randomization_test")
        self.horizontalLayout_7.addWidget(self.pb_run_randomization_test)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 570, 27))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bed intersection"))
        self.label_2.setText(_translate("MainWindow", "<b>Behavioral strings</b>"))
        self.pb_select_behav_strings_file.setText(_translate("MainWindow", "Load from file"))
        self.label_4.setText(_translate("MainWindow", "<b>Behavioral strings statistics</b>"))
        self.pb_statistics.setText(_translate("MainWindow", "Generate statistics"))
        self.pb_save_observed_matrix.setText(_translate("MainWindow", "Save observed transition matrix"))
        self.label_6.setText(_translate("MainWindow", "<b>Flow diagram</b>"))
        self.label_8.setText(_translate("MainWindow", "Edge labels"))
        self.rb_percent_after_behav.setText(_translate("MainWindow", "% of transitions after behavior"))
        self.label_9.setText(_translate("MainWindow", "Cut-off"))
        self.le_cutoff_transition_after_behav.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "%"))
        self.rb_percent_total_transitions.setText(_translate("MainWindow", "% of total transitions"))
        self.label_10.setText(_translate("MainWindow", "Cut-off"))
        self.le_cutoff_total_transition.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "%"))
        self.rb_fraction_after_behav.setText(_translate("MainWindow", "fraction of transitions after behavior"))
        self.pb_graphviz_script.setText(_translate("MainWindow", "Generate GraphViz script"))
        self.pb_flow_diagram.setText(_translate("MainWindow", "Generate flow diagram"))
        self.label_5.setText(_translate("MainWindow", "<b>Randomization test</b>"))
        self.cb_block_first_behavior.setText(_translate("MainWindow", "Block first behavior"))
        self.cb_block_last_behavior.setText(_translate("MainWindow", "Block last behavior"))
        self.label_7.setText(_translate("MainWindow", "Excluded transitions"))
        self.label.setText(_translate("MainWindow", "Number of randomizations"))
        self.leNumberRandomizations.setText(_translate("MainWindow", "100"))
        self.label_3.setText(_translate("MainWindow", "Number of cores to use"))
        self.pb_run_randomization_test.setText(_translate("MainWindow", "Run randomization test"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

